#!/bin/bash

# Use the current directory name as the mvim server name (if the directory name is not empty, e.g. root)
printf -v current_dir '%s' "${PWD##*/}"
if [ -n "$current_dir" ]; then
	MVIMARGS="--servername '$current_dir'"
fi

# Add -remote-tab-silent if arguments specified
if [ $# -gt 0 ]; then
	MVIMARGS="$MVIMARGS --remote-silent" ;
fi

eval mvim "$MVIMARGS $@"
