#!/bin/bash

vimCmd='mvim'

show_usage() {
cat <<USAGE
Usage: ${0##*/} [-h] [-t] [--] <files/paths list>
       -h Show this help
       -t Use vim's remote-tab
USAGE
}

# Parse options
# Reset OPTIND in case getopts was used previously
OPTIND=1
while getopts "ht" opt; do
	case "$opt" in
		h)
			show_usage
			exit 0
			;;
		t)
			remoteOption='remote-tab-silent'
			;;
	esac
done
shift "$((OPTIND-1))" # Shift off the options and optional --.

# Use a vim server whose name will be based on the current path.
# If inside a Git repo, use the repo top level directory name.
# Otherwise, use the current working directory name.
workingDir='ROOT'
git rev-parse 2> /dev/null  # `git rev-parse` will exit with a non-zero status code when called outside a git repo
if [ $? -eq 0 ]; then
	# We are in a Git repo
	workingDir=$(basename $(git rev-parse --show-toplevel))
else
	printf -v workingDir '%s' "${PWD##*/}"
fi

# $workingDir will be empty if at the root directory; set a ROOT servername
serverName="${workingDir:-ROOT}"

vimOpts="--servername '$serverName'"

# Set up options and filenames if a file (arg) list is specified
if [ $# -gt 0 ]; then
	vimOpts="$vimOpts --${remoteOption:-remote-silent}"

	# Retain literal whitespace in filenames by wrapping in quotes
	filesList=()
	while (( "$#" )); do
		filesList+=("'$1'")
		shift
	done

	# When there isn't an existing server instance with the specified name, vim will first start a new instance
	# with a [No Name] buffer before loading the specified files for editing. We want to delete that empty buffer
	# so that there isn't an extra buffer loaded.
	# fgrep: search for a fixed (non-RE) pattern
	# options:
		# i: ignore-case
		# q: quiet
		# x: match only entire lines
	if ! $vimCmd --serverlist | fgrep -iqx "$serverName"; then
		# A new server instance will be started; delete the empty buffer
		vimOpts="$vimOpts +bdelete1"
	fi
fi


eval "$vimCmd $vimOpts ${filesList[@]}"
